### ISSUE TITLE
How to generate salient object input image?

### ISSUE THREAD

**Issue by tsbiosky** [Cold-Winter/BachGAN#1]
Can you provide some instructions for running the  code ,thank you !

**Comment by ych133** [comment]
We will release the script to generate salient object input soon.

**Comment by ych133** [comment]
> Can you provide some instructions for running the code ,thank you !

We will release the script to generate salient object input soon.

**Comment by Cold-Winter** [comment]
Sorry to go back to you so late.
If you want to get the foreground boxes:
check https://github.com/Cold-Winter/BachGAN/blob/master/data/cityscapes_dataset.py#L85 for cityscapes
and https://github.com/Cold-Winter/BachGAN/blob/master/data/ade20k_dataset.py#L72 for for ade20k

I am working on simplifying the retrieval process, will update the instructions once I finish it.
