### ISSUE TITLE
Training BachGAN on Coco using Coco-Stuff maps?

### ISSUE THREAD

**Issue by mkumar10** [Cold-Winter/BachGAN#2]
Did the authors try training BachGAN on coco? And if not are there any particular things I would need to be careful about to set it up for a new dataset.

**Comment by Cold-Winter** [comment]
Sorry to get back to you lately. The reason we do not run experiment on COCO-stuff is that we do not have the computation resource. It takes 5 days to train the model on COCO-stuff with 4 V100. Please let me know if you have further questions.

**Comment by mkumar10** [comment]
I see thanks for the response. I will let you know for further questions - thanks a lot!
