### ISSUE TITLE
Coco-stuff Retrieval Results

### ISSUE THREAD

**Issue by mkumar10** [Cold-Winter/BachGAN#5]
@Cold-Winter do you have the COCO-stuff retrieval results? Seems like retrieval is being the bottleneck and if you are able share it. Thanks

**Comment by Cold-Winter** [comment]
Hi Sorry, currently i do not have the retrieval results for COCO-stuff. But you can do it by yourself with scripts/retrival_ious_city_halfset/retrival_seg_halfset.py

**Comment by mkumar10** [comment]
But @Cold-Winter  did you try to do it? It seems like it will be pretty slow - if memory bank is 1/4th ~ approx 30k images in memory bank for 80 classes - seems like its coming out to be about 2-2.5 min per image - which is about 200k min - even if I use 10 processes as you did its 20k min - any way to scale it better?

**Comment by Cold-Winter** [comment]
Yeah. You are right. Sorry for the messy code. I do not have time to fix it for large scale dataset like COCO-stuff. But I would like to suggest you to compute the IOU between boxes and segments in parallel or increase the number of processes.
